// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tartarus_final.Models;

namespace Tartarus_final.Migrations
{
    [DbContext(typeof(NasContext))]
    partial class NasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tartarus_final.Models.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ObavijestId")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ObavijestId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("Tartarus_final.Models.Poruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PorukaId")
                        .HasColumnType("int");

                    b.Property<string>("PrimalacEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("posiljalacEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PorukaId");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("Tartarus_final.Models.Obavijest", b =>
                {
                    b.HasOne("Tartarus_final.Models.Obavijest", null)
                        .WithMany("Obavijesti")
                        .HasForeignKey("ObavijestId");
                });

            modelBuilder.Entity("Tartarus_final.Models.Poruka", b =>
                {
                    b.HasOne("Tartarus_final.Models.Poruka", null)
                        .WithMany("Poruke")
                        .HasForeignKey("PorukaId");
                });
#pragma warning restore 612, 618
        }
    }
}
